---
# remiのリポジトリをインストール
- name: install remi repository
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm state=present
# php70のインストール
- name: install php70
  yum: name={{ item }} enablerepo=remi,remi-test state=present
  with_items:
  - php70
  - php70-php
  - php70-php-mbstring
  - php70-php-gd
  - php70-php-pgsql
  - php70-php-mcrypt
  - php70-php-intl
  - php70-php-opcache
  - php70-php-pdo
  - php70-php-json
  - php70-php-pecl-zip
  - php70-php-xml
# ここから https://gist.github.com/debility/8838906 を反映
- name: config PHP
  copy: src=99-my.ini dest=/etc/opt/remi/php70/php.d/99-my.ini
# ここまで https://gist.github.com/debility/8838906 を反映
- name: config OPCache
  lineinfile: dest=/etc/opt/remi/php70/php.d/10-opcache.ini regexp="opcache\.enable_cli=" line="opcache.enable_cli=1"
- name: memory_limit size up
  lineinfile: dest=/etc/opt/remi/php70/php.ini regexp="memory_limit =" line="memory_limit = 512M"
- name: post_max_size size up
  lineinfile: dest=/etc/opt/remi/php70/php.ini regexp="post_max_size =" line="post_max_size = 10M"
- name: upload_max_filesize size up
  lineinfile: dest=/etc/opt/remi/php70/php.ini regexp="upload_max_filesize =" line="upload_max_filesize = 10M"
# ログイン時に有効化する
- name: config for login
  copy: src=enablephp70.sh dest=/etc/profile.d/enablephp70.sh mode=0644
- name: restart httpd
  service: name=httpd state=restarted
